<script>
import { computed, defineComponent, h } from 'vue';
import { deserializeTree } from '../../_layout/inspector/serialize.js';
import { isTextNode } from '../../_layout/inspector/componentRegistry.js';

// Recursive renderer for the spec tree.
const RenderNode = defineComponent({
	name: 'RenderNode',
	props: { node: { type: Object, required: true } },
	setup(props) {
		return () => {
			const n = props.node;
			if (isTextNode(n)) return n.text;
			const tag = n.component || 'div';
			const children = (n.children || []).map((c) =>
				isTextNode(c) ? c.text : h(RenderNode, { node: c, key: c.id }),
			);
			return h(tag, { ...(n.props || {}) }, children.length ? children : undefined);
		};
	},
});

// Rehydrate a saved spec into a live tree of components. Use this to render
// content stored in a database, fetched from an API, or generated by the
// studio export.
//
//   <ElRenderer :spec="loadedFromDb" />
export default defineComponent({
	name: 'ElRenderer',
	props: { spec: { type: Object, required: true } },
	setup(props) {
		const tree = computed(() => {
			try { return deserializeTree(props.spec); } catch { return null; }
		});
		return () =>
			tree.value
				? h(RenderNode, { node: tree.value })
				: h('div', {
					class: 'rounded-xl border border-dashed border-skin-border bg-skin-surface/40 p-4 text-xs text-skin-muted',
				}, 'Unable to render the provided spec.');
	},
});
</script>
