export const sideNavLinks = [
	{
		label: 'Tooling',
		items: [
			{ to: '/elements/theming', label: 'Theming', tag: 'New' },
			{ to: '/elements/components/studio', label: 'Studio', tag: 'Pro' },
			{ to: '/elements/components/playground', label: 'Playground' },
		],
	},
	{
		label: 'Components',
		items: [
			{ to: '/elements/components/button', label: 'Button' },
			{ to: '/elements/components/menu', label: 'Menu', tag: 'New' },
			{ to: '/elements/components/listbox', label: 'Listbox', tag: 'New' },
			{ to: '/elements/components/dropdown', label: 'Dropdown' },
			{ to: '/elements/components/dialog', label: 'Dialog' },
			{ to: '/elements/components/drawer', label: 'Drawer', tag: 'New' },
			{ to: '/elements/components/tabs', label: 'Tabs' },
			{ to: '/elements/components/toggle', label: 'Toggle' },
			{ to: '/elements/components/tooltip', label: 'Tooltip' },
			{ to: '/elements/components/accordion', label: 'Accordion' },
			{ to: '/elements/components/combobox', label: 'Combobox' },
			{ to: '/elements/components/autocomplete', label: 'Autocomplete' },
			{ to: '/elements/components/popover', label: 'Popover', tag: 'New' },
			{ to: '/elements/components/toast', label: 'Toast', tag: 'New' },
			{ to: '/elements/components/command-palette', label: 'Command palette', tag: 'New' },
		],
	},
	{
		label: 'Visual',
		items: [
			{ to: '/elements/visual/card', label: 'Card', tag: 'New' },
		],
	},
	{
		label: 'Forms',
		items: [
			{ to: '/elements/components/checkbox', label: 'Checkbox', tag: 'New' },
			{ to: '/elements/components/radio-group', label: 'Radio group', tag: 'New' },
			{ to: '/elements/components/text-input', label: 'Text input' },
			{ to: '/elements/components/textarea-input', label: 'Textarea' },
			{ to: '/elements/components/number-input', label: 'Number input' },
			{ to: '/elements/components/select-input', label: 'Select input' },
			{ to: '/elements/components/boolean-input', label: 'Boolean input' },
			{ to: '/elements/components/color-input', label: 'Color input' },
			{ to: '/elements/components/list-input', label: 'List input' },
		],
	},
	{
		label: 'Headless',
		items: [
			{ to: '/elements/headless', label: 'Overview' },
			{ to: '/elements/headless/dropdown', label: 'Dropdown' },
			{ to: '/elements/headless/dialog', label: 'Dialog' },
			{ to: '/elements/headless/drawer', label: 'Drawer' },
			{ to: '/elements/headless/popover', label: 'Popover' },
			{ to: '/elements/headless/tabs', label: 'Tabs' },
			{ to: '/elements/headless/toggle', label: 'Toggle' },
			{ to: '/elements/headless/tooltip', label: 'Tooltip' },
			{ to: '/elements/headless/accordion', label: 'Accordion' },
			{ to: '/elements/headless/combobox', label: 'Combobox' },
			{ to: '/elements/headless/autocomplete', label: 'Autocomplete' },
		],
	},
];
